Client table
alexandervishnivetskiy/docker-symfony pull request #3
Opened 2018-08-20 13:26 UTC by alexandervishnivetskiy

Add new Entity client, add ManyToOne association, add 'show All Reports Of Client' and 'delete report' feature

2018-08-20 15:53 UTC, ruff3d requested changes

2018-08-20 15:53 UTC, ruff3d commented on web/reports/reports.csv
> -257,"report ",client,53,"Test description"
зачем комитил этот файл?

2018-08-20 15:53 UTC, ruff3d commented on web/src/Repository/ClientRepository.php
> +    */
это не оставляй в коде

2018-08-21 06:55 UTC, alexandervishnivetskiy commented on web/reports/reports.csv
> -257,"report ",client,53,"Test description"
убрал с репозитория, добавил в .gitingone

2018-08-21 10:24 UTC, closed without merging